### ISSUE TITLE
Create a GitHub Action to compile with caxa

### ISSUE THREAD

**Issue by leafac** [leafac/caxa#24]
This would, for example, abstract away the complexity of emulating ARM & creating releases, and so forth.

Idea given by @mfbx9da4

**Comment by SOVLOOKUP** [comment]
I just made it in my project, I think it can help you.

https://github.com/SOVLOOKUP/starry/blob/master/.github/workflows/node.js.yml

It includes:

1. Compile and compress source code (using tsup)
2. Minimize dependencies size (based on [dependencies-resolver](https://github.com/SOVLOOKUP/dependencies-resolver))
3. [Cross-platform compilation](https://github.com/SOVLOOKUP/starry/blob/master/scripts/release.mjs)
4. Automated release

**Comment by matteosacchetto** [comment]
I'm not that familiar with writing custom actions, but I was able to build arm and amr64 executables using docker.

Here is a snippet to do so for arm:
```yaml
jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Setup QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Build the image
      - name: Build with caxa for arm
        run: |
          docker run --rm --platform linux/arm/v7 -v $(pwd):/app --workdir="/app" --user 1000:1000 node:lts sh -c "npm ci; npx caxa ... "
```
To do the same on arm64, simply change `--platform linux/arm/v7` to `--platform linux/arm64`
